---
  - name: start elasticsearch
    systemd:
      name: elasticsearch
      enabled: yes
      state: started

  - name: restart elasticsearch
    systemd:
      name: elasticsearch
      state: restarted

  - name: stop elasticsearch
    systemd:
      name: elasticsearch
      state: stopped

  - name: start nginx
    systemd:
      name: nginx
      enabled: yes
      state: started

  - name: restart nginx
    systemd:
      name: nginx
      state: restarted

  - name: stop nginx
    systemd:
      name: nginx
      state: stopped

  - name: start kibana
    systemd:
      name: kibana
      enabled: yes
      state: started

  - name: restart kibana
    systemd:
      name: kibana
      state: restarted

  - name: stop kibana
    systemd:
      name: kibana
      state: stopped
